# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache dependencies untuk mempercepat proses build
        
  # Step 3: Install dependencies
    - run: npm ci
      
  # Step 4: Run linting
    - name: Run linter
      run: npm run lint
    
    - run: npm run build --if-present
      
  # Step 5: Run tests
    - name: Run tests
    - run: npm test

  # Langkah Deploy FTP setelah Build dan Test Sukses
    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        ftp-port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_TARGET_DIR }} # Direktori tujuan di server FTP
